### ISSUE TITLE
Logging in with a ?ReturnUrl= seems to break login

### ISSUE THREAD

**Issue by firescript** [Sitefinity/feather-widgets#1668]
When I log in with no query string present the login works as expected. When I try to log in on the page with the url set to:
`/login?ReturnUrl=/explore/search` 

it breaks and returns to the same login page with an updated url containing:

`/login?ReturnUrl=%2fexplore%2fsearch&sf_cntrl_id=ctl00%24cph_main%24C011`

I am not authenticated, only when i remove the query string and reload the page will it process the login properly.

**Comment by ElenaGaneva** [comment]
Hello firescript,

This issue is not reproducible with latest versions of Sitefinity 11.0+ so I'm closing this item.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
