### ISSUE TITLE
Space getting added to default list and detail views for camel-cased dynamic content types

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/feather-widgets#1979]
If I have a content type called "TestType", for example, the auto-generated views are called "List.Test Type" and "Detail.Test Type". To override those views using razor, you have to create cshtml files called "List.Test Type.cshtml" and "Detail.Test Type.cshtml". It's very bad practice to have to name your views with spaces.

**Comment by ElenaGaneva** [comment]
Hello OndeVai,

This issue is no longer reproducible with latest versions of Sitefinity. Now when I create type named TestType the view names are List.TestType.cshtml and Details.TestType.cshtml.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
