### ISSUE TITLE
Link selector > Page from this site - the current site is not selected in the dropdown

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather-widgets#203]
1. Multisite with the following sites : site2 , testsite
2. You are in testsite
3. Create a page with content block - open the link selector and switch to page selector
As a result: testsite is not selected , but site2 is displayed instead
Expected: the current site should be selected in the drop-down
NOTE: related to https://github.com/Sitefinity/feather/issues/186 (Feather Content block: "Insert a link" > "Page from this site" - current language should be selected)

**Comment by NadezhdaPetrova** [comment]
Behavior: Site 1 (default) with EN (default) and DE; Site 2 with EN and BG (default)

Case 1: Open EN page in Site 1. Site 1 is selected from the sites dropdown and the page language (EN) is selected from the languages dropdown
Change to Site 2. Then the selected language must be EN, because you are in EN page

Case 2: Open BG page in Site 2. Site 2 is selected from the sites dropdown and the BG is selected from the languages dropdown (this is the language of the current page)
Change to Site 1. Then EN will be selected for language because Site 1 does not have BG language and then will select the default language for Site 1 (EN).
